services:
  perlite:
    image: sec77/perlite:latest
    container_name: perlite
    restart: unless-stopped
    environment:
      - NOTES_PATH=Demo
      - HIDE_FOLDERS=docs,private,trash
      - HIDDEN_FILE_ACCESS=false
      - LINE_BREAKS=true
      - ABSOLUTE_PATHS=false
      - ALLOWED_FILE_LINK_TYPES=pdf,mp4
      - DISABLE_POP_HOVER=false
      - SHOW_TOC=true
      - SHOW_LOCAL_GRAPH=true
      - HOME_FILE=README
      - FONT_SIZE=15
      # Set HTML_SAFE_MODE to false to support footnotes
      - HTML_SAFE_MODE=false
      - TEMP_PATH=/tmp
      - SITE_TITLE=Demo
      - SITE_TYPE=article
      - SITE_URL=
      - SITE_IMAGE=
      - SITE_DESC=
      - SITE_NAME=Perlite
      - SITE_TWITTER=https://x.com/
      - SITE_LOGO=perlite.svg
      - SITE_HOMEPAGE=https://perlite.secure77.de/
      - SITE_GITHUB=https://github.com/
    volumes:
      - ./perlite/Demo:/var/www/perlite/Demo:ro
      # This branch supports footnotes (non-safe mode). 
      # Download the content.php and ParsedownExtra.php files in this branch.
      # then map them to the container.
      - ./content.php:/var/www/perlite/content.php:ro
      - ./ParsedownExtra.php:/var/www/perlite/ParsedownExtra.php:ro

  web:
    image: nginx:stable
    container_name: perlite_web
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./web/config/perlite.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from: 
      - perlite       
    depends_on:
      - perlite

